// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const ACTIVATE_WIDGET_LOADER = 'ACTIVATE_WIDGET_LOADER'

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const CHANGE_PWD = 'CHANGE_PWD'
export const SEND_USERNAME_FOR_FORGOT_PWD = 'SEND_USERNAME_FOR_FORGOT_PWD'
export const SHOW_CONFIRM_NEW_PWD_FORM = 'SHOW_CONFIRM_NEW_PWD_FORM'
export const RESET_USER_PWD = 'RESET_USER_PWD'
export const CLEAR_FORGET_PWD_USERNAME = 'CLEAR_FORGET_PWD_USERNAME'
export const ADMIN_CHANGE_USER_PASSWORD = 'ADMIN_CHANGE_USER_PASSWORD'
export const MODAL_CONFIRM_LOADER = 'MODAL_CONFIRM_LOADER'

export const GOOGLE_CAPTCHA_TOKEN = 'GOOGLE_CAPTCHA_TOKEN'
export const REFRESH_GOOGLE_CAPTCHA_TOKEN = 'REFRESH_GOOGLE_CAPTCHA_TOKEN'

export const CREATE_COMPONENT = 'CREATE_COMPONENT'
export const FETCH_COMPONENTS = 'FETCH_COMPONENTS'
export const FETCHED_COMPONENTS = 'FETCHED_COMPONENTS'
export const CREATE_POLICY = 'CREATE_POLICY'
export const FETCH_POLICIES = 'FETCH_POLICIES'
export const FETCHED_POLICIES = 'FETCHED_POLICIES'
export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_ROLE = 'CREATE_ROLE'
export const FETCH_ROLES = 'FETCH_ROLES'
export const FETCHED_ROLES = 'FETCHED_ROLES'
export const SHOW_GROUP_LIST = 'SHOW_GROUP_LIST'
export const FETCH_GROUPS = 'FETCH_GROUPS'
export const FETCHED_GROUPS = 'FETCHED_GROUPS'
export const SHOW_POLICY_LIST = 'SHOW_POLICY_LIST'
export const FETCH_GROUP_POLICIES = 'FETCH_GROUP_POLICIES'
export const FETCHED_GROUP_POLICIES = 'FETCHED_GROUP_POLICIES'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const HIDE_GROUPS_AND_POLICIES = 'HIDE_GROUPS_AND_POLICIES'
export const SAVE_USER_TOKEN = 'SAVE_USER_TOKEN'
export const SHOW_MODULES_LIST = 'SHOW_MODULES_LIST'
export const FETCH_ADMIN_ROLES_LIST = 'FETCH_ADMIN_ROLES_LIST'
export const FETCHED_ADMIN_ROLES_LIST = 'FETCHED_ADMIN_ROLES_LIST'
export const FETCH_SUB_ROLES = 'FETCH_SUB_ROLES'
export const FETCHED_SUB_ROLES = 'FETCHED_SUB_ROLES'
export const FETCH_ADMIN_GROUPS = 'FETCH_ADMIN_GROUPS'
export const FETCHED_ADMIN_GROUPS = 'FETCHED_ADMIN_GROUPS'
export const FETCH_POLICIES_AND_COMPONENTS = 'FETCH_POLICIES_AND_COMPONENTS'
export const FETCHED_POLICIES_AND_COMPONENTS = 'FETCHED_POLICIES_AND_COMPONENTS'
export const FETCH_GROUPS_AND_POLICIES = 'FETCH_GROUPS_AND_POLICIES'
export const FETCHED_GROUPS_AND_POLICIES = 'FETCHED_GROUPS_AND_POLICIES'
export const FETCH_USERS_LIST = 'FETCH_USERS_LIST'
export const FETCHED_USERS_LIST = 'FETCHED_USERS_LIST'
export const FETCH_USERNAMES_LIST = 'FETCH_USERNAMES_LIST'
export const FETCHED_USERNAMES_LIST = 'FETCHED_USERNAMES_LIST'
export const EDIT_COMPONENT = "EDIT_COMPONENT"
export const EDIT_GROUP = "EDIT_GROUP"
export const EDIT_POLICY = "EDIT_POLICY"
export const EDIT_ROLE = "EDIT_ROLE"
export const FETCH_USER_GROUPS_AND_POLICIES = 'FETCH_USER_GROUPS_AND_POLICIES'
export const FETCHED_USER_GROUPS = 'FETCHED_USER_GROUPS'
export const FETCHED_USER_POLICIES = 'FETCHED_USER_POLICIES'
export const CLEAR_ROLES = 'CLEAR_ROLES'
export const CLEAR_GROUPS = 'CLEAR_GROUPS'
export const CLEAR_POLICIES = 'CLEAR_POLICIES'
export const TOGGLE_COMPONENT = 'TOGGLE_COMPONENT'
export const TOGGLE_USER = 'TOGGLE_USER'
export const TOGGLE_ROLE = 'TOGGLE_ROLE'
export const TOGGLE_POLICY = 'TOGGLE_POLICY'
export const TOGGLE_GROUP = 'TOGGLE_GROUP'
export const SEARCH_COLUMN = 'SEARCH_COLUMN'
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'

//Dashboard Tabs
export const ADD_TAB = 'ADD_TAB'
export const ACTIVE_TAB_PANES = 'ACTIVE_TAB_PANES'
export const SET_ACTIVE_PANE = 'SET_ACTIVE_PANE'
export const REMOVE_TAB = 'REMOVE_TAB'
export const CLEAR_TABS = 'CLEAR_TABS'



// Audit Logs
export const FETCH_AUDIT_LOGS = 'FETCH_AUDIT_LOGS'
export const FETCHED_AUDIT_LOGS = 'FETCHED_AUDIT_LOGS'
export const CLEAR_AUDIT_LOGS = 'CLEAR_AUDIT_LOGS'


// Alerts
export const FETCH_ALERTS = 'FETCH_ALERTS'
export const FETCHED_ALERTS = 'FETCHED_ALERTS'
export const CREATE_ALERT = 'CREATE_ALERT'
export const EDIT_ALERT = 'EDIT_ALERT'
export const DELETE_ALERT = 'DELETE_ALERT'
export const FETCH_ACTIVE_ALERTS = 'FETCH_ACTIVE_ALERTS'
export const FETCHED_ACTIVE_ALERTS = 'FETCHED_ACTIVE_ALERTS'
export const SHOW_ALERTS_POPUP = 'SHOW_ALERTS_POPUP'

export const DELETE_USER = 'DELETE_USER'
export const FETCH_DOWNLOAD_USER_LIST = 'FETCH_DOWNLOAD_USER_LIST'
export const FETCHED_DOWNLOAD_USER_LIST = 'FETCHED_DOWNLOAD_USER_LIST'
export const CLEAR_DOWNLOAD_USER_LIST = 'CLEAR_DOWNLOAD_USER_LIST'

//AVIDTAGS
export const FETCH_ALLTAGS = 'FETCH_ALLTAGS'
export const FETCHED_ALLTAGS = 'FETCHED_ALLTAGS'
export const EDIT_ALLTAGS = "EDIT_ALLTAGS"
export const CREATE_TAG = "CREATE_TAG"
export const EDIT_TAG = "EDIT_TAG"

