export const CIPDashboardJson = {
  "Account Information": {
    path: "Account",
    component: "Account",
    order: 1,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Subscription Information": {
    path: "Subscription",
    component: "Subscription",
    order: 2,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Contact Information": {
    path: "Contact",
    component: "Contact",
    order: 3,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Billing Summary": {
    path: "Billing",
    component: "Billing",
    order: 4,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Address Information": {
    path: "Address",
    component: "Address",
    order: 5,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Interaction Information": {
    path: "Interaction",
    component: "Interaction",
    isWinlead: false,
    order: 6,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Winlead Buttons": {
    path: "KeyFieldsInfo",
    component: "KeyFieldsInfo",
    order: 4,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Case Information": {
    path: "Cases",
    component: "Cases",
    order: 7,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "PDPA Information": {
    path: "Pdpa",
    component: "Pdpa",
    order: 8,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Portal Account Information": {
    path: "PortalAccountInformation",
    component: "PoratlAccountInformation",
    order: 11,
    xl: 12,
    lg: 12,
    md: 12,
    sm: 12,
    xs: 24,
  },

  "Payment Information": {
    path: "WinleadPayment",
    component: "WinleadPayment",
    order: 5,
    xl: 12,
    lg: 12,
    md: 12,
    sm: 12,
    xs: 24,
  },
  "Financial Information": {
    path: "WinleadFinancialInfo",
    component: "WinleadFinancialInfo",
    order: 9,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Collection Bucket": {
    path: "WinleadCollectionBucket",
    component: "WinleadCollectionBucket",
    order: 3,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Free Preview": {
    button: true,
    path: "WinleadFreePreviewList",
    component: "Free Preview List",
    icon: "FundViewOutlined",
    title: "Free Preview",
    order: 9,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },

  "Disconnection Information": {
    button: true,
    path: "DisconnectionList",
    component: "Disconnection List",
    icon: "DisconnectOutlined",
    title: "Disconnection",
    order: 9,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "WL Billing Summary": {
    button: true,
    title: "Billing Summary",
    path: "BillingInfo/index",
    component: "BillingInfo",
    icon: "AuditOutlined",
    order: 9,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  "Flash Messages": {
    button: true,
    title: "Flash Messages",
    icon: "ThunderboltOutlined",
    path: "WinleadFlashMessagesList",
    component: "Flash Message List",
    order: 9,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
  Interaction: {
    title: "Interaction ",
    button: true,
    path: "Interaction",
    component: "Interaction",
    icon: "FormOutlined",
    isWinlead: true,
    order: 9,
    xl: 6,
    lg: 6,
    md: 6,
    sm: 12,
    xs: 24,
  },
};
